default_platform(:ios)

platform :ios do
  desc "Upload build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    build_number = latest_testflight_build_number(api_key: api_key) + 1

    increment_build_number(
      build_number: build_number
    )

    build_app(
      scheme: "MindMory",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end

