name: Upload TestFlight Build

on:
  push:
    branches:
      - main-testflight

jobs:
  testflight:
    runs-on: macos-latest

    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
      FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby dependencies
        run: bundle install

      - name: Xcode Version
        run: xcodebuild -version

      - name: List Schemes
        run: xcodebuild -list -project MindMory.xcodeproj

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings -scheme MindMory -project MindMory.xcodeproj

      - name: Show Code Signing Identities
        run: security find-identity -v -p codesigning

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: bundle exec fastlane beta